### ISSUE TITLE
ssp_server: error while loading shared libraries

### ISSUE THREAD

**Issue by alitokur** [moetsi/Sensor-Stream-Pipe#13]
it's working well with ubuntu 20.04 but I get the following error when I try it on ubuntu 18.04

ssp_server: error while loading shared libraries: libswresamample.so.3: cannot open shared object file: No such file or directory

Is there any solution for ubuntu 18.04?

cheers

**Comment by adammpolak** [comment]
Sorry @alitokur unfortunately with the extensions we have done with SSP (iOS extension, Unity plugin extension) we have been a bit resource-constrained to also support backward compatibility to 18.04.

Are you able to move forward on your project using 20.04?

**Comment by jaykim305** [comment]
I had the same issue. I solved it by exporting LD_LIBRARY_PATH.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${workspaceFolder}/build/_deps/ssp_dep-src/ffmpeg/lib/`.
