### ISSUE TITLE
Can I also get a ARKIT pose?

### ISSUE THREAD

**Issue by knsjoon** [moetsi/Sensor-Stream-Pipe#15]
Dear Sensor-Stream-Pipe team,

Hello, as I want to use ARKIT rgb / depth / pose data to do 3D reconstruction on my local computer, equipped with GPU, 
I wonder if Sensor-Stream-Pipe can be modified in anyway to obtain live- arkit poses relative to a world-coordinate frame that ARKIT initializes. 

Thank you in advance!

**Comment by adammpolak** [comment]
> Dear Sensor-Stream-Pipe team,
> 
> Hello, as I want to use ARKIT rgb / depth / pose data to do 3D reconstruction on my local computer, equipped with GPU, I wonder if Sensor-Stream-Pipe can be modified in anyway to obtain live- arkit poses relative to a world-coordinate frame that ARKIT initializes.
> 
> Thank you in advance!

@knsjoon yes that is possible. You would need to extend the current iOS plugin that grabs the RGB to also grab the 3D pose from ARKit.

You could then extend SSP iPhone Reader to include the ability to pull this data in and stream as a new frame struct.
