### ISSUE TITLE
I have a Problem installing in JETSON  NANO.

### ISSUE THREAD

**Issue by DongBumKim** [moetsi/Sensor-Stream-Pipe#17]
Hi.

I'm trying to install SSP Server in Jetson Nano, but I'm keep having this error when i try to "make" it.

[ 90%] Built target ssp
make[3]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so', needed by 'bin/ssp_server'.  Stop.
CMakeFiles/Makefile2:196: recipe for target 'CMakeFiles/ssp_server.dir/all' failed
make[2]: *** [CMakeFiles/ssp_server.dir/all] Error 2
CMakeFiles/Makefile2:203: recipe for target 'CMakeFiles/ssp_server.dir/rule' failed
make[1]: *** [CMakeFiles/ssp_server.dir/rule] Error 2
Makefile:176: recipe for target 'ssp_server' failed
make: *** [ssp_server] Error 2

Jetson Nano is an ARM-based device, so there is no x86_64-linux-gnu.

Is there any way I can solve this problem?

Thanks!

**Comment by adammpolak** [comment]
I believe you need gtk for OpenCV window support. Considering you are on a jetson nano I assume you don't need GUI ont he device.

You could try and rebuild the dependencies but without OpenCV windowing that requires gtk, the code for building the OpenCV dependency is here: https://github.com/moetsi/Sensor-Stream-Pipe/blob/297581ff7b050bc4e97c1861c1f3e4f0955a24b9/3rdparty/build_lin_dep.sh#L69


or possibly you can just not require highgui support here: https://github.com/moetsi/Sensor-Stream-Pipe/blob/297581ff7b050bc4e97c1861c1f3e4f0955a24b9/CMakeLists.txt#L136
that might do the trick 


You would also need to remove building any source files that use OpenCV windowing here or edit them to not use that functionality: https://github.com/moetsi/Sensor-Stream-Pipe/blob/297581ff7b050bc4e97c1861c1f3e4f0955a24b9/CMakeLists.txt#L218

**Comment by adammpolak** [comment]
Assuming this is closed
